server:
  http_port: 8081
  mode: "debug"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "waf"
  password: "waf123456"
  database: "waf"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "waf-secret-key-change-in-production"
  expire: 3600

waf:
  rate_limit_window: 60
  max_requests: 100

log:
  level: "debug" 