server:
  port: ":8080"
  mode: "debug"

database:
  dsn: "root:password@tcp(localhost:3306)/waf?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: "waf-secret-key-change-in-production"
  expire: 3600

waf:
  rate_limit_window: 60
  max_requests: 100

log:
  level: "debug" 